Repository wecode-bootcamp-korea/41-1st-IWEA-frontend, pull requests merged in 2023-01, with the labels that each got.

#7 [41기:김우성] ADD: footer레이아웃 구현
  public/images/arrow.png
  public/images/facebook.png
  public/images/instagram.png
  public/images/kakaotalk.png
  public/images/kt.png
  public/images/world.png
  public/images/youtube.jpg
  src/Router.js
  src/components/Footer.jsx
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#3 [41기 김철호] ADD: Login 레이아웃, 유효성검사, 서버에서 토큰 받아오기
  package-lock.json
  package.json
  src/config.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.scss
  src/styles/mixin.scss
Labels: 완료

#8 [41기 김철호] ADD: Nav 레이아웃 구현
  public/images/cart.png
  public/images/close.png
  public/images/delivery.png
  public/images/enter.png
  public/images/logo.png
  public/images/menu.png
  public/images/store.png
  public/images/user.png
  public/index.html
  src/Router.js
  src/components/Header.jsx
  src/components/Header.scss
  src/pages/Home/Header.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/components/Header.jsx
  src/pages/Home/components/Header.scss
Labels: 멘토 리뷰 요청

#9 [41기 임가림] Add : Payment page 레이아웃 구현
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/component/PaymentAside/PaymentAside.jsx
  src/pages/Payment/component/PaymentAside/PaymentAside.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfo.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfo.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoItem.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoItem.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoModal/PaymentInfoModal.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoModal/PaymentInfoModal.scss
Labels: 리뷰 진행 중

#4 [41기 임가림] Add : 데이터 렌더링 및 UI 수정
  .env
  .gitignore
  package-lock.json
  package.json
  public/data/list-data.json
  public/images/ProductDetail/basket.png
  public/images/ProductDetail/cart.png
  public/images/ProductDetail/close.png
  public/images/ProductDetail/delivery-truck.png
  public/images/ProductDetail/free-icon-add-cart-7326992.png
  public/images/ProductDetail/heart-color.png
  public/images/ProductDetail/heart.png
  public/images/ProductDetail/shop.png
  src/Router.js
  src/config.js
  src/config/config.js
  src/pages/Login/Login.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/component/ProductAside/ProductAside.jsx
  src/pages/ProductDetail/component/ProductAside/ProductAside.scss
  src/pages/ProductDetail/component/ProductAside/ProductAsideBuy/ProductAsideBuy.jsx
  src/pages/ProductDetail/component/ProductAside/ProductAsideBuy/ProductAsideBuy.scss
  src/pages/ProductDetail/component/ProductAside/ProductAsideInfo/ProductAsideInfo.jsx
  src/pages/ProductDetail/component/ProductAside/ProductAsideInfo/ProductAsideInfo.scss
  src/pages/ProductDetail/component/ProductItem/ProductImg/ProductImg.jsx
  src/pages/ProductDetail/component/ProductItem/ProductImg/ProductImg.scss
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductDesc/ProductDesc.jsx
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductDesc/ProductDesc.scss
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfo.jsx
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfo.scss
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfoModal/ProductInfoModal.jsx
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfoModal/ProductInfoModal.scss
  src/pages/ProductDetail/component/ProductItem/ProductItem.jsx
  src/pages/ProductDetail/component/ProductItem/ProductItem.scss
  src/pages/ProductDetail/component/ProductSlide/ProductSlide.jsx
  src/pages/ProductDetail/component/ProductSlide/ProductSlide.scss
  src/pages/ProductDetail/component/ProductSlide/ProductSlideItem/ProductSlideItem.jsx
  src/pages/ProductDetail/component/ProductSlide/ProductSlideItem/ProductSlideItem.scss
  src/styles/color.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#15 [41기 김철호] Modify: 회원가입창 레이아웃 수정
  src/pages/SignUp/SignUp.scss
Labels: 멘토 리뷰 요청

#6 [41기 김성재] ADD: Product Page 레이아웃 및 기능 구현
  package-lock.json
  public/data/mock.json
  public/images/Home/logo-basket 2.png
  public/images/Home/logo-camera 2.png
  public/images/Home/logo-person 2.png
  src/Router.js
  src/images/basket.png
  src/images/btn-leftArrow.png
  src/images/btn-rightArrow.png
  src/pages/Home/Home.jsx
  src/pages/Home/components/HomeMain.jsx
  src/pages/Home/components/HomeMain.scss
  src/pages/Product/Product.jsx
  src/pages/Product/Product.scss
  src/pages/Product/components/AlertModal/AlertModal.jsx
  src/pages/Product/components/AlertModal/AlertModal.scss
  src/pages/Product/components/Carousel/Carousel.jsx
  src/pages/Product/components/Carousel/Carousel.scss
  src/pages/Product/components/Carousel/CarouselConstData.js
  src/pages/Product/components/ProductList.jsx
  src/pages/Product/components/ProductList.scss
  src/pages/Product/components/ProductSort.jsx
  src/pages/Product/components/ProductSort.scss
Labels: 멘토 리뷰 요청

#13 [41기 김성재] ADD: Home 페이지 레이아웃 수정
  public/images/Home/btn-leftArrow.png
  public/images/Home/btn-rightArrow.png
  public/images/Home/home-event-arrow.png
  public/images/Home/home-event1.png
  public/images/Home/home-event2.png
  public/images/Home/home-event3.png
  src/components/Carousel.jsx
  src/components/Carousel.scss
  src/components/CarouselConstData.js
  src/images/arrow-b.png
  src/images/arrow-b2.png
  src/pages/Home/Home.jsx
  src/pages/Home/components/HomeBanner.jsx
  src/pages/Home/components/HomeBanner.scss
  src/pages/Home/components/HomeEvent.js
  src/pages/Home/components/HomeEvent.jsx
  src/pages/Home/components/HomeEvent.scss
  src/pages/Home/components/HomeEventCard.jsx
  src/pages/Home/components/HomeEventCard.scss
  src/pages/Home/components/HomeGrid.jsx
  src/pages/Home/components/HomeGrid.scss
  src/pages/Home/components/HomeMain.scss
Labels: 완료

#10 [41기 임가림] Add : Side Modal창 구현
  public/images/close.png
  src/components/Header.jsx
  src/components/SideModal/SideModal.jsx
  src/components/SideModal/SideModal.scss
  src/components/SideModal/component/SideModalInfo/SideModalInfo.jsx
  src/components/SideModal/component/SideModalInfo/SideModalInfo.scss
  src/components/SideModal/component/SideModalList/SideModalList.jsx
  src/components/SideModal/component/SideModalList/SideModalList.scss
Labels: 완료

#19 [41기 임가림] Modify : sidemodal page scss 수정
  src/config/config.js
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfoModal/ProductInfoModal.jsx
  src/pages/ProductDetail/component/ProductItem/ProductInfo/ProductInfoModal/ProductInfoModal.scss
Labels: 멘토 리뷰 요청

#11 [41기 김철호] Add: Sidebar 레이아웃 + 슬라이드 기능 추가
  src/components/Header.jsx
  src/components/SideBar.jsx
  src/components/SideBar.scss
  src/pages/Cart/Cart.jsx
  src/pages/Home/Home.jsx
Labels: 완료

#18 [41기 김철호 Cart 레이아웃 + 기능추가
  public/data/cartList.json
  public/images/trash.png
  public/index.html
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.scss
  src/pages/Cart/components/CartProducts.jsx
  src/pages/Cart/components/CartProducts.scss
  src/pages/Cart/components/CartSideBar.jsx
  src/pages/Cart/components/CartSideBar.scss
  src/pages/Cart/components/PaymentModal.jsx
  src/pages/Cart/components/PaymentModal.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfo.scss
Labels: 멘토 리뷰 요청

#21 [41기 김철호] Modify: 휴대폰 인풋 예시 변경
  src/pages/SignUp/SignUp.jsx
Labels: 완료

#23 [41기 김철호] Add : 카트아이콘에 수량표시 추가
  src/components/Header.jsx
  src/components/Header.scss
Labels: 완료

#20 [41기 임가림] Feature/payment page 데이터 통신 및 렌더링
  src/pages/Payment/Payment.jsx
  src/pages/Payment/Payment.scss
  src/pages/Payment/component/PaymentAside/PaymentAside.jsx
  src/pages/Payment/component/PaymentAside/PaymentAside.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfo.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfo.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoData/PaymentInfoData.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoData/PaymentInfoData.scss
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoItem.jsx
  src/pages/Payment/component/PaymentInfo/PaymentInfoItem/PaymentInfoItem.scss
  src/pages/Product/Product.jsx
Labels: 멘토 리뷰 요청

#24 [41기 임가림] sidemodal창 안나오는 오류 수정 및 스타일 속성 수정
  public/images/SideModal/iwea-logo.png
  src/components/Header.jsx
  src/components/SideModal/SideModal.jsx
  src/components/SideModal/SideModal.scss
  src/components/SideModal/component/SideModalInfo/SideModalInfo.jsx
Labels: 완료

#27 [41기 김철호] Modify: nav바 error핸들링
  src/components/Header.jsx
Labels: 완료

#31 [41기 임가림] Feature/cart page 배송문구변경 및 에러핸들링 추가
  src/pages/Cart/Cart.jsx
  src/pages/Cart/components/CartSideBar.jsx
Labels: 멘토 리뷰 요청
